/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionsBar: typeof import('./components/ActionsBar.vue')['default']
    CategoryDialog: typeof import('./components/CategoryDialog.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    QBtn: typeof import('quasar')['QBtn']
    QCheckbox: typeof import('quasar')['QCheckbox']
    QDate: typeof import('quasar')['QDate']
    QDialog: typeof import('quasar')['QDialog']
    QDrawer: typeof import('quasar')['QDrawer']
    QExpansionItem: typeof import('quasar')['QExpansionItem']
    QHeader: typeof import('quasar')['QHeader']
    QIcon: typeof import('quasar')['QIcon']
    QInput: typeof import('quasar')['QInput']
    QItem: typeof import('quasar')['QItem']
    QItemSection: typeof import('quasar')['QItemSection']
    QLayout: typeof import('quasar')['QLayout']
    QPage: typeof import('quasar')['QPage']
    QPageContainer: typeof import('quasar')['QPageContainer']
    QPopupProxy: typeof import('quasar')['QPopupProxy']
    QSelect: typeof import('quasar')['QSelect']
    QSpace: typeof import('quasar')['QSpace']
    QTable: typeof import('quasar')['QTable']
    QTd: typeof import('quasar')['QTd']
    QTime: typeof import('quasar')['QTime']
    QToolbar: typeof import('quasar')['QToolbar']
    QToolbarTitle: typeof import('quasar')['QToolbarTitle']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
